fix Error: MISSING_COMMA: detected by covscan
This commit fixes the following errors found by conscan,

    Error: MISSING_COMMA: [#def3]
    python-dmidecode-3.12.2/src/dmidecode.c:1375: missing_comma: In the initialization of "upgrade", a suspicious concatenated string ""Socket BGA1288Socket rPGA988B"" is produced due to a missing comma between lines.
    python-dmidecode-3.12.2/src/dmidecode.c:1375: remediation: Did you intend to separate these two string literals with a comma?
    # 1373|                   "Socket LGA1567",
    # 1374|                   "Socket PGA988A",
    # 1375|->                 "Socket BGA1288"        /* 0x20 */
    # 1376|                   "Socket rPGA988B",
    # 1377|                   "Socket BGA1023",

    Error: MISSING_COMMA: [#def4]
    python-dmidecode-3.12.2/src/dmidecode.c:1843: missing_comma: In the initialization of "type", a suspicious concatenated string ""64-way Set-associative20-way Set-associative"" is produced due to a missing comma between lines.
    python-dmidecode-3.12.2/src/dmidecode.c:1843: remediation: Did you intend to separate these two string literals with a comma?

    Error: MISSING_COMMA: [#def6]
    python-dmidecode-3.12.2/src/dmidecode.c:2868: missing_comma: In the initialization of "type", a suspicious concatenated string ""DDR3FBD2"" is produced.
    python-dmidecode-3.12.2/src/dmidecode.c:2868: remediation: Did you intend to separate these two string literals with a comma?
    # 2866|                   "Reserved",
    # 2867|                   "Reserved",
    # 2868|->                 "DDR3"
    # 2869|                   "FBD2"          /* 0x19 */
    # 2870|           };
    # 1841|                   "32-way Set-associative",
    # 1842|                   "48-way Set-associative",
    # 1843|->                 "64-way Set-associative"        /* 0x0D */
    # 1844|                   "20-way Set-associative"        /* 0x0E */