fix Error: CONSTANT_EXPRESSION_RESULT detected by covscan
This commit fixes the following error found by conscan,

    Error: CONSTANT_EXPRESSION_RESULT (CWE-569): [#def1]
    python-dmidecode-3.12.2/src/dmidecode.c:225: logical_vs_bitwise: The expression "16 && i < h->length - (row << 4)" is suspicious because it performs a Boolean operation on a constant other than 0 or 1.
    #  223|                   memset(tmp_s, 0, (h->length * 2) + 2);
    #  224|
    #  225|->                 for(i = 0; i < (16 && i < h->length - (row << 4)); i++) {
    #  226|                           snprintf(tmp_s + strlen(tmp_s), (h->length * 2)-strlen(tmp_s),
    #  227|                                    "0x%02x", (h->data)[(row << 4) + i]);